version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network
